name: securebank

services:
  postgres:
    image: postgres:17-alpine
    container_name: securebank-postgres

    environment:
      POSTGRES_DB: secure_bank_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

#    ports:
#      - "127.0.0.1:5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: securebank-api:local
    container_name: securebank-api

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/secure_bank_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}

    ports:
      - "127.0.0.1:8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:8080/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

    restart: unless-stopped

volumes:
  postgres_data: