spring:
  application:
    name: SecureBankAPI

  datasource:
    url: jdbc:postgresql://localhost:5432/secure_bank_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
jwt:
  secret: "8a5e7e92-02a9-493f-91bf-f3a9b9d2ceb6"
  expiration: 86400000